
/**
 * This is a constant string file, all the string(text showing on screen) used in webapp are rest here
 */
export const STRINGS = {
  HEADER_LOGO_TITLE: "| Developers",
  HEADER_SUBMENU_WHY_MARVEL: "Why Marvel",
  ENTERPRISE: "Enterprise",
  PRICING: "Pricing",
  SIGN_IN: "Sign in",
  SIGN_UP_FREE: "Sign up free",
  LANDING_PAGE_TITLE_FUTURE: "Let's build the future of design, now.",
  LANDINGPAGE_SUBTITLE: 'Create amazing tools and integrations for 2 million users or customise Marvel for your team.',
  SUBMIT_YOUR_APP: "Submit your app",
  VIEW_API_DOCS: 'View API Docs',
  BECOME_A_PARTNER: 'Become a partner',
  VIEW_INTEGRATIONS: 'View Integrations',
  EXPERIENCE_FREEDOM_TITLE: 'Experience the freedom to build features, right away.',
  EXPERIENCE_DESCRIPTION: 'You can now harness components of our platform and build powerful integrations for our 2 million users - or simply just for your team.',
  DEDICATED_API_TEAM: 'Dedicated API Team',
  OUR_TEAM_DESCRIPTION: "Our team are available for user's questions via  our Slack Developer Community and Email",
  OUR_API_USES_GRAPH_QL: 'Our API uses Graph QL',
  HANDLING_SERVER_DESCRIPTION: "No handling server side. Get may API's response in a single request.",
  SUPERCHARGE_YOUR_WORKFLOW: 'Supercharge your workflow',
  AUTOMATE_WORKFLOWS_DESCRIPTION: " Automate workflows, integrate and analyse data and take Marvel to the next level.",
  SHOWCASE_YOUR_APP_TITLE: "Showcase your app in our integrations directory",
  BUILDING_SOMETHINGS_DESCRIPTION: " Building somethings special? we're always looking to work with partners who wants to help the world bring their ideas to life.",
  A_SLACK_DESCRIPTION: " A slack-bot for creating and managing prototypes",
  FOOTER_OVERVIEW: 'Overview',
  FOOTER_WHY_MARVEL: 'Why Marvel',
  FOOTER_ENTERPRISE: 'Enterprise',
  FOOTER_PRICE: 'Pricing',
  FOOTER_REQUEST_A_DEMO: 'Request a demo',
  FOOTER_EXPLORE: 'Explore',
  FOOTER_APPS: 'Apps',
  FOOTER_DEVELOPER_API: 'Developer API',
  FOOTER_FEATURES: 'Features',
  FOOTER_WIREFRAMING: 'Wireframing',
  FOOTER_DESIGN: 'Design',
  FOOTER_PROTOTYPING: 'Prototyping',
  FOOTER_COLLABORATION: 'Collaboration',
  FOOTER_HANDOFF: 'Handoff',
  FOOTER_INTEGRATIONS: 'Integrations',
  FOOTER_SKETCH_PLUGIN: 'Sketch Plugin',
  FOOTER_SUPPORT: 'Support',
  FOOTER_HEL_CENTER: 'Hel Center',
  FOOTER_TERMS_OF_SERVICE: 'Terms of Service',
  FOOTER_PRIVACY: 'Privacy',
  FOOTER_SECURITY: 'Security',
  FOOTER_MARVEL: 'Marvel',
  FOOTER_BLOG: 'Blog',
  FOOTER_OUR_TEAM: 'Our Team',
  FOOTER_CONTACT_US: 'Contact Us',
  FOOTER_SUCCESS_STORIES: 'Success Stories',
  FOOTER_BRAND_GUIDELINES: 'Brand Guidelines',
  FOOTER_FOLLOW: 'Follow',
  FOOTER_TWITTER: 'Twitter',
  FOOTER_DRIBBBLE: 'Dribbble',
  FOOTER_FACEBOOK: 'Facebook',
  FOOTER_GITHUB: 'Github',
  FOOTER_WORKABLE: 'Workable',
  VIEW_THE_DOCS: 'View the docs',
  MANAGE_YOUR_APPS: 'Manage your apps',
  TODO: 'To Do',
};
